#!/bin/bash -e
autoreconf -i
PATH=$HOME/.ghcup/bin:$PATH
ghcup upgrade
ghcup install cabal latest
ghcup set cabal latest
ghcup install ghc latest
ghcup set ghc latest
cabal update
cabal v1-install --only-dependencies --enable-tests
cabal v1-configure --enable-tests
cabal v1-test
cabal v1-haddock
