#!/bin/bash -e
PATH=$HOME/.ghcup/bin:$PATH
ghcup set cabal latest
ghcup set ghc latest
cabal v1-install --only-dependencies --enable-tests
cabal v1-configure --enable-tests
cabal v1-test
cabal v1-haddock
