#!/bin/bash -e
if [ "$1" == "-b" ]
then stack build --no-test --no-bench --no-haddock fourmolu
fi

for f in `find -name '*.hs' -not -path '*.stack-work/*' -not -path '*/dist/*' | grep -xvf .format.ignore`
do `stack path --local-install-root`/bin/fourmolu -i -o -XPatternSynonyms $f || exit
done
