#!/bin/bash -e
git clean -dXf
git pull
autoreconf -i
PATH=$HOME/.ghcup/bin:$PATH
ghcup upgrade
ghcup install cabal latest
ghcup set cabal latest
for c in 8.10.7 9.0.2 9.2.2
do
ghcup install ghc $c
ghcup set ghc $c
cabal update
cabal v1-install --only-dependencies --enable-tests
cabal v1-configure --enable-tests
cabal v1-test
cabal v1-haddock
done
echo OK
