#!/bin/bash -e
git clean -dXf
#git pull
autoreconf -i
PATH=$HOME/.ghcup/bin:$PATH
ghcup upgrade
ghcup install cabal latest
ghcup set cabal latest

# check supported versions
for c in 9.8.4 9.10.1 9.12.2
do
ghcup install ghc $c
ghcup set ghc $c
cabal update
cabal v1-install --only-dependencies --enable-tests
cabal v1-configure --enable-tests
cabal v1-test
cabal v1-haddock
done

# check unsupported versions do not select this version of time
for c in 9.4.8 9.6.7
do
ghcup install ghc $c
ghcup set ghc $c
cabal update
if cabal v1-configure --enable-tests;
then
    echo "time incorrectly selected with unsupported GHC version $c"
    exit 1
else
    echo "time correctly deselected with unsupported GHC version $c"
fi
done
echo OK
