resolver: lts-22.12
packages:
- '.'
allow-newer: true

build:
    keep-going: true
    haddock: true
    haddock-deps: false
    test: true
    test-arguments:
        additional-args: [--hide-successes]

extra-deps:
- process-1.6.18.0
- unix-2.8.5.0
- directory-1.3.8.3

ghc-options:
    "$locals": -Werror -Wincomplete-uni-patterns -Wincomplete-record-updates -Wredundant-constraints -Wcompat -Wnoncanonical-monad-instances
